name: EVM Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "LICENSE"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "LICENSE"

jobs:
  state-tests:
    name: StateTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - uses: astral-sh/setup-uv@v4
      - run: pnpm run build
      - name: Download test fixtures
        working-directory: packages/evm
        run: pnpm run fixtures

      - run: pnpm tsx ./test/cli.ts --format=state_test
        working-directory: packages/evm

  blockchain-tests:
    name: BlockchainTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - uses: astral-sh/setup-uv@v4
      - run: pnpm run build
      - name: Download test fixtures
        working-directory: packages/evm
        run: pnpm run fixtures
      - run: pnpm tsx ./test/cli.ts --format=blockchain_test
        working-directory: packages/evm
